stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make bootstrap-live
    - make build
  cache:
    paths:
      - vendor/
      - _site/
  artifacts:
    paths:
      - _site/

deploy_live:
  stage: deploy
  script:
    - rsync -arvO --delete _site/ /srv/http/mayeu.me
  environment:
    name: live
    url: https://mayeu.me
  only:
    - master
