image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LC_ALL: C.UTF-8

stages:
  - build

Build website:
  stage: build
  script:
    - apk add make nodejs bash npm jq
    - make build
