# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
theme: jekyll-hackhack

t:
  en:
    title: Hi, I'm Mayeu
    description: I mostly do computering, tea :tea:, and travelling
  fr:
    title: Salut, je suis Mayeu
    description: Je fais principalement de l'ordinateur, du thé :tea:, et des voyages

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mayeu.me" # the base hostname & protocol for your site, e.g. http://example.com

email: m@mayeu.me
social:
  - service: github
    username: Mayeu
    link: https://github.com/Mayeu
  - service: twitter
    username: Mayeu
    link: https://twitter.com/Mayeu

# Build settings
livereload: true
name: Mayeu
permalink: /blog/:title/
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-data
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor
  - test-site

defaults:
  - scope:
      path: ""
    values:
      image: /assets/me.jpg
