# Site settings
title: Mayeu's website
email: m@mayeu.me
description: > # this means to ignore newlines until "baseurl:"
  Mayeu's personal website. You can expect content on sysadmin, automation, privacy, libre software and tea.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mayeu.me" # the base hostname & protocol for your site
twitter_username: Mayeu
github_username:  Mayeu

# Build settings
markdown: kramdown

# Server setting
host: 0.0.0.0
  #
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

exclude:
- README.md
- vendor
- Makefile
- Gemfile
- Gemfile.lock
